# configure your midi controller here.
# though knowing what your OS will name your hardware controller varies system to system
# in my case linux names the xone:k2 with a trailing space lol *shrugs*
["XONE:K2 "]
# these are ordered by the sorted file names of the plugin functions 
# the file prefixed by 1_ is the first item in this function
fns = [
	24, # M Button Spiral
	25, # N Button V2
	26, # O Button Waves
	27, # P Button Audio
	31  # L Button Solid
	    # ??       Something
]
name              = "XONE:K2 "
intensity         = 16 # fader_1
decay_factor      = 17 # fader_2
lum_mod           = 18 # fader_3
time_dialation    = 19 # fader_4
reset             = 36 # A Button
backwards         = 37 # B Button
is_fft            = 38 # C Button
is_listening_midi = 52 # 1_encoder_push
is_saving_preset  = 53 # 2_encoder_push
decay_param       = 10 # 3_middle_knob
modulo_param      = 14 # 3_bottom_knob
# this is what my mac assigns the name without space...while linux has trailing spaces *shrugs*
["XONE:K2"]
# these are ordered by the sorted file names of the plugin functions 
# the file prefixed by 1_ is the first item in this function
fns = [
	24, # M Button Spiral
	25, # N Button V2
	26, # O Button Waves
	27, # P Button Audio
	31  # L Button Solid
	    # ??       Something
]
name              = "XONE:K2"
intensity         = 16 # fader_1
decay_factor      = 17 # fader_2
lum_mod           = 18 # fader_3
time_dialation    = 19 # fader_4
reset             = 36 # A Button
backwards         = 37 # B Button
is_fft            = 38 # C Button
is_listening_midi = 52 # 1_encoder_push
is_saving_preset  = 53 # 2_encoder_push
decay_param       = 10 # 3_middle_knob
modulo_param      = 14 # 3_bottom_knob

# this is the output sent from ableton live
# interestingly all the intensity values are 64
# despite setting the intensity in ableton to 127
["WINE ALSA Output #1"]
# these are ordered by the sorted file names of the plugin functions 
# the file prefixed by 1_ is the first item in this function
fns = [
	24, # C0  Spiral
	25, # C#0 V2
	26, # D0  Waves
	12, # C-1 Audio
	27  # D#0 Solid
	    # ??       Something
]
name              = "WINE ALSA Output #1"
intensity         = 0  # ??
decay_factor      = 0  # ??
lum_mod           = 0  # ??
time_dialation    = 0  # ??
reset             = 13 # C#-1
backwards         = 0  # ??
is_fft            = 0  # ??
is_listening_midi = 0  # ??
is_saving_preset  = 0  # ??
decay_param       = 0  # ??
modulo_param      = 0  # ??

["Pioneer DJ XDJ-RX2"]
# these are ordered by the sorted file names of the plugin functions 
# the file prefixed by 1_ is the first item in this function
fns = [
	24, # M Button Spiral
	25, # N Button V2
	26, # O Button Waves
	27, # P Button Audio
	31  # L Button Solid
	    # ??       Something
]
name              = "Pioneer DJ XDJ-RX2"
intensity         = 33 # right jog wheel nudge 
decay_factor      = 0  # fader_2
lum_mod           = 0  # fader_3
time_dialation    = 0  # fader_4
reset             = 0  # A Button
backwards         = 0  # B Button
is_fft            = 0  # C Button
is_listening_midi = 0  # 1_encoder_push
is_saving_preset  = 0  # 2_encoder_push
decay_param       = 0  # 3_middle_knob
modulo_param      = 0  # 3_bottom_knob

["Arturia KeyLab Essential 61 MID"]
fns = [
	40,
	41,
	26
]
name              = "Arturia KeyLab Essential 61 MID"
intensity         = 73
decay_factor      = 0
lum_mod           = 0
time_dialation    = 19
reset             = 0
backwards         = 0
is_fft            = 0
decay_param       = 0
modulo_param      = 0
is_listening_midi = 0
is_saving_preset  = 0
